--- #YAML:1.0
name:               Astro-Correlate
version:            1.0
abstract:           Class for cross-correlating astronomical catalogues.
author:
    - Brad Cavanagh <brad.cavanagh@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Astro::Catalog:    0
    File::SearchPath:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
