# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-Correlate
version:      0.01
version_from: Correlate.pm
installdirs:  site
requires:
    Astro::Catalog:                0
    File::SearchPath:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
